version: "3"

services:
  phoenix:
    build: .
    volumes:
      - ./src:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami1.tls=true"
      - "traefik.http.routers.whoami1.rule=PathPrefix(`/dashboard`,`/phoenix`,`/live`)&&Host(`world-dashboard.duckdns.org`)"
      - "traefik.http.routers.whoami1.entrypoints=websecure"
      - "traefik.http.routers.whoami1.tls.certresolver=myresolver"
      - "traefik.docker.network=public-server"
    networks:
      - public-server

  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - public-server

networks:
  public-server:
    external:
      name: public-server_default

